seqs_root: /home/uni/Data/drl_exposure_ctrl
sequences: 
  -
    seq_name: train_indoor
  -
    seq_name: train_outdoor
  -
    seq_name: train_parking
states: 
      - 
        expo_t: 50
        gain: 0
      - 
        expo_t: 198
        gain: 0
      - 
        expo_t: 1008
        gain: 0
      - 
        expo_t: 5007
        gain: 0
      - 
        expo_t: 19994
        gain: 0
